version: "3"

services:
    runner:
        build:
            context: .
        environment:
            - USERNAME=coma-toast
            - REPO=gh-runner-docker
            - TOKEN=ADLV3F4STQJ223UHWZS4FMDDLSSIY
        volumes:
            - data:/actions-runner
            - /var/run/docker.sock:/var/run/docker.sock
volumes:
    data:
