version: "3"

services:
    runner:
        build: .
        environment:
            - USERNAME=coma-toast
            - REPO=gh-runner-docker
            - TOKEN=ADLV3FZDIBCFDCZB3PZTLDLDG64HM
        volumes:
            - data:/actions-runner
            - ./EntryPoint.sh:/EntryPoint.sh

volumes:
    data:
