version: "3"

services:
  runner:
    build: .
    environment:
      - VERSION=2.297.0
      - USERNAME=coma-toast
      - REPO=gh-runner-docker
      - TOKEN=ADLV3F4VPZR7XXS372FHJZTDGYMJA
    volumes:
      - ./temp:/temp
      - ./EntryPoint.sh:/EntryPoint.sh
